version: "3.8"
services:
  bookstack-mcp-http:
    build:
      context: .
    container_name: bookstack-mcp-http
    environment:
      - PORT=3054
      - TRANSPORT=http
      - BS_URL=https://knowledge.oculair.ca
      - BS_TOKEN_ID=${BS_TOKEN_ID}
      - BS_TOKEN_SECRET=${BS_TOKEN_SECRET}
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    ports:
      - "3054:3054"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.create_connection(('localhost', 3054), 5); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bookstack-mcp

networks:
  bookstack-mcp:
    driver: bridge
