version: "3.8"
services:
  bookstackmcp:
    build:
      context: .
      args:
        TRANSPORT: http
    image: oculair/bookstackmcp:http
    ports:
      - 3054:3054
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=3054
      - TRANSPORT=http
      - BS_URL=${BS_URL}
      - BS_TOKEN_ID=${BS_TOKEN_ID}
      - BS_TOKEN_SECRET=${BS_TOKEN_SECRET}
      - NODE_ENV=${NODE_ENV:-production}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3054/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks: {}